-- V18: 国际化（i18n）支持 — 新增 uuid/i18n 字段
ALTER TABLE teams ADD COLUMN uuid TEXT DEFAULT NULL;
ALTER TABLE teams ADD COLUMN i18n TEXT NOT NULL DEFAULT '{}';
ALTER TABLE agents ADD COLUMN i18n TEXT NOT NULL DEFAULT '{}';
ALTER TABLE rooms ADD COLUMN i18n TEXT NOT NULL DEFAULT '{}';
ALTER TABLE role_templates ADD COLUMN i18n TEXT NOT NULL DEFAULT '{}';

-- 为 uuid 列创建唯一索引（允许 NULL，SQLite 对 NULL 不视为重复）
CREATE UNIQUE INDEX IF NOT EXISTS idx_teams_uuid ON teams(uuid) WHERE uuid IS NOT NULL;
